apiVersion: networking.k8s.io/v1
kind: Ingress

metadata:
  name: lovable-main-ingress
  namespace: lovable-core
  annotations:
    nginx.ingress.kubernetes.io/proxy-read-timeout: "3600"
    nginx.ingress.kubernetes.io/proxy-send-timeout: "3600"
    nginx.ingress.kubernetes.io/ssl-redirect: "true"

spec:
  ingressClassName: nginx

  tls:
    - hosts:
        - "promptforge.deepakjaiswar.dev"
        - "api.promptforge.deepakjaiswar.dev"
        - "*.previews.promptforge.deepakjaiswar.dev"
      secretName: promptforge-tls

  rules:
    # PromptForge Frontend
    - host: "promptforge.deepakjaiswar.dev"
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: lovable-frontend
                port:
                  number: 80

    # Generated App Previews
    - host: "*.previews.promptforge.deepakjaiswar.dev"
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: lovable-me-proxy
                port:
                  number: 80

    # API Gateway
    - host: "api.promptforge.deepakjaiswar.dev"
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: api-gateway
                port:
                  number: 80